# pdf_generator.py
"""
Generate beautiful PDF from processed notes
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib.colors import HexColor, black, white
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
import os
from datetime import datetime

def create_styles():
    """Create custom styles for the PDF"""
    
    styles = getSampleStyleSheet()
    
    # Title style
    styles.add(ParagraphStyle(
        name='CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=30,
        alignment=TA_CENTER,
        textColor=HexColor('#1a1a2e')
    ))
    
    # Heading style
    styles.add(ParagraphStyle(
        name='CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        spaceBefore=20,
        spaceAfter=10,
        textColor=HexColor('#16213e')
    ))
    
    # Subheading style
    styles.add(ParagraphStyle(
        name='CustomSubheading',
        parent=styles['Heading3'],
        fontSize=13,
        spaceBefore=15,
        spaceAfter=8,
        textColor=HexColor('#0f3460')
    ))
    
    # Body text style
    styles.add(ParagraphStyle(
        name='CustomBody',
        parent=styles['Normal'],
        fontSize=11,
        leading=16,
        alignment=TA_JUSTIFY,
        textColor=HexColor('#333333')
    ))
    
    # Bullet style
    styles.add(ParagraphStyle(
        name='CustomBullet',
        parent=styles['Normal'],
        fontSize=11,
        leading=16,
        leftIndent=20,
        bulletIndent=10,
        textColor=HexColor('#333333')
    ))
    
    # Box style (for key points, tips)
    styles.add(ParagraphStyle(
        name='BoxContent',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=HexColor('#1a1a2e')
    ))
    
    return styles

def generate_pdf(data, output_path):
    """
    Generate a beautiful PDF from processed notes data
    
    data = {
        "topic": str,
        "subject": str,
        "cleaned_notes": str,
        "expanded_notes": str,
        "summary": str,
        "key_concepts": list,
        "analogies": list,
        "questions": list,
        "diagrams": list  # paths to diagram images
    }
    """
    
    print(f"\n📄 Generating PDF: {output_path}")
    
    # Create document
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm
    )
    
    styles = create_styles()
    story = []
    
    # ═══════════════════════════════════════
    # TITLE PAGE
    # ═══════════════════════════════════════
    
    story.append(Spacer(1, 2*inch))
    
    # Title
    story.append(Paragraph(
        data.get("topic", "Study Notes"),
        styles['CustomTitle']
    ))
    
    story.append(Spacer(1, 0.3*inch))
    
    # Subject
    story.append(Paragraph(
        f"Subject: {data.get('subject', 'General')}",
        ParagraphStyle(
            'SubjectLine',
            parent=styles['Normal'],
            fontSize=14,
            alignment=TA_CENTER,
            textColor=HexColor('#666666')
        )
    ))
    
    story.append(Spacer(1, 0.5*inch))
    
    # Date
    story.append(Paragraph(
        f"Generated on: {datetime.now().strftime('%B %d, %Y')}",
        ParagraphStyle(
            'DateLine',
            parent=styles['Normal'],
            fontSize=11,
            alignment=TA_CENTER,
            textColor=HexColor('#888888')
        )
    ))
    
    story.append(Spacer(1, 0.2*inch))
    
    # Generated by badge
    story.append(Paragraph(
        "📚 Generated by Notes Agent | AI-Powered Study Assistant",
        ParagraphStyle(
            'Badge',
            parent=styles['Normal'],
            fontSize=10,
            alignment=TA_CENTER,
            textColor=HexColor('#4a4a4a')
        )
    ))
    
    story.append(PageBreak())
    
    # ═══════════════════════════════════════
    # TABLE OF CONTENTS
    # ═══════════════════════════════════════
    
    story.append(Paragraph("📋 Table of Contents", styles['CustomHeading']))
    story.append(Spacer(1, 0.2*inch))
    
    toc_items = [
        "1. Summary",
        "2. Key Concepts",
        "3. Detailed Notes",
        "4. Analogies & Examples",
        "5. Diagrams",
        "6. Probable Exam Questions"
    ]
    
    for item in toc_items:
        story.append(Paragraph(f"    {item}", styles['CustomBody']))
        story.append(Spacer(1, 0.1*inch))
    
    story.append(PageBreak())
    
    # ═══════════════════════════════════════
    # SUMMARY
    # ═══════════════════════════════════════
    
    story.append(Paragraph("📝 1. Summary", styles['CustomHeading']))
    story.append(Spacer(1, 0.1*inch))
    
    summary = data.get("summary", "No summary available.")
    story.append(Paragraph(summary, styles['CustomBody']))
    story.append(Spacer(1, 0.3*inch))
    
    # ═══════════════════════════════════════
    # KEY CONCEPTS
    # ═══════════════════════════════════════
    
    story.append(Paragraph("🎯 2. Key Concepts", styles['CustomHeading']))
    story.append(Spacer(1, 0.1*inch))
    
    concepts = data.get("key_concepts", [])
    for concept in concepts:
        story.append(Paragraph(f"• {concept}", styles['CustomBullet']))
    
    story.append(Spacer(1, 0.3*inch))
    
    # ═══════════════════════════════════════
    # DETAILED NOTES
    # ═══════════════════════════════════════
    
    story.append(Paragraph("📖 3. Detailed Notes", styles['CustomHeading']))
    story.append(Spacer(1, 0.1*inch))
    
    notes = data.get("expanded_notes", data.get("cleaned_notes", ""))
    
    # Convert markdown-style formatting to paragraphs
    for para in notes.split('\n\n'):
        if para.strip():
            # Check if it's a heading
            if para.strip().startswith('##'):
                clean_heading = para.replace('#', '').strip()
                story.append(Paragraph(clean_heading, styles['CustomSubheading']))
            elif para.strip().startswith('-') or para.strip().startswith('•'):
                story.append(Paragraph(para.strip(), styles['CustomBullet']))
            else:
                story.append(Paragraph(para.strip(), styles['CustomBody']))
            story.append(Spacer(1, 0.1*inch))
    
    story.append(Spacer(1, 0.2*inch))
    
    # ═══════════════════════════════════════
    # ANALOGIES
    # ═══════════════════════════════════════
    
    analogies = data.get("analogies", {}).get("analogies", [])
    
    if analogies:
        story.append(PageBreak())
        story.append(Paragraph("💡 4. Analogies & Examples", styles['CustomHeading']))
        story.append(Spacer(1, 0.2*inch))
        
        for analogy in analogies:
            # Concept name
            story.append(Paragraph(
                f"<b>{analogy.get('concept', 'Concept')}</b>",
                styles['CustomSubheading']
            ))
            
            # Analogy
            story.append(Paragraph(
                f"🔗 <i>Analogy:</i> {analogy.get('analogy', '')}",
                styles['CustomBody']
            ))
            
            # Example
            story.append(Paragraph(
                f"📌 <i>Example:</i> {analogy.get('example', '')}",
                styles['CustomBody']
            ))
            
            story.append(Spacer(1, 0.2*inch))
    
    # ═══════════════════════════════════════
    # DIAGRAMS
    # ═══════════════════════════════════════
    
    diagrams = data.get("diagrams", [])
    
    if diagrams:
        story.append(PageBreak())
        story.append(Paragraph("📊 5. Diagrams", styles['CustomHeading']))
        story.append(Spacer(1, 0.2*inch))
        
        for diagram in diagrams:
            try:
                img_path = diagram.get("path", "")
                if os.path.exists(img_path):
                    img = Image(img_path, width=5*inch, height=3.5*inch)
                    story.append(img)
                    
                    # Caption
                    story.append(Paragraph(
                        f"<i>{diagram.get('description', 'Diagram')}</i>",
                        ParagraphStyle(
                            'Caption',
                            parent=styles['Normal'],
                            fontSize=10,
                            alignment=TA_CENTER,
                            textColor=HexColor('#666666')
                        )
                    ))
                    story.append(Spacer(1, 0.3*inch))
            except:
                pass
    
    # ═══════════════════════════════════════
    # QUESTIONS
    # ═══════════════════════════════════════
    
    questions = data.get("questions", {}).get("questions", [])
    
    if questions:
        story.append(PageBreak())
        story.append(Paragraph("❓ 6. Probable Exam Questions", styles['CustomHeading']))
        story.append(Spacer(1, 0.2*inch))
        
        for i, q in enumerate(questions, 1):
            q_type = q.get("type", "QUESTION")
            marks = q.get("marks", "")
            question = q.get("question", "")
            
            story.append(Paragraph(
                f"<b>Q{i}. [{q_type}] ({marks} marks)</b>",
                styles['CustomSubheading']
            ))
            
            story.append(Paragraph(question, styles['CustomBody']))
            
            # Options for MCQ
            if q_type == "MCQ":
                options = q.get("options", [])
                for j, opt in enumerate(options):
                    story.append(Paragraph(
                        f"    {chr(97+j)}) {opt}",
                        styles['CustomBullet']
                    ))
            
            # Hint
            hint = q.get("hint", "")
            if hint:
                story.append(Paragraph(
                    f"💡 <i>Hint: {hint}</i>",
                    ParagraphStyle(
                        'Hint',
                        parent=styles['Normal'],
                        fontSize=10,
                        leftIndent=20,
                        textColor=HexColor('#0066cc')
                    )
                ))
            
            story.append(Spacer(1, 0.2*inch))
    
    # ═══════════════════════════════════════
    # BUILD PDF
    # ═══════════════════════════════════════
    
    doc.build(story)
    print(f"✅ PDF generated: {output_path}")
    
    return output_path